### ISSUE TITLE
Weight for Long regression and Short regression

### ISSUE THREAD

**Issue by DavidaLi0725** [chaisemartinPackages/twowayfeweights#5]
As your paper de Chaisemartin & D’Haultfoeuille (2023) mentioned the weight for long regression and short regression, how to apply this twowayfeweights? Although other_treatments could be added in it, what's the difference code for long regression and short regression?

**Comment by chaisemartinPackages** [comment]
We have uploaded the [replication package](https://github.com/chaisemartinPackages/ReplicationPackages) for the application in section 6 of [de Chaisemartin & D’Haultfoeuille (2023)](https://www.sciencedirect.com/science/article/pii/S0304407623001963), there you can find how the weights for the two different regressions can be computed. Alternatively, you can retrieve the replication package directly from Professor de Chaisemartin's [website](https://sites.google.com/site/clementdechaisemartin/).
